---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    aws_k8s_teardown: true
    aws_lb:
      ports:
      - name: ingress
      - name: api
  roles:
    - aws-instances
