---
- hosts: masters
  become: yes
  roles:
    - tools
    - containerd
    - crictl
    - k8s
- hosts: remote
  become: yes
  tasks:
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      with_list:
        - index.html
        - nginx.yaml
        - pgsql-set.yaml
        - pvc-man.yaml
        - pvc-rwx.yaml
        - pvc.yaml
        - pv.yaml
