---
- hosts: masters
  become: yes
  roles:
    - tools
    - containerd
    - crictl
    - k8s
- hosts: remote
  become: yes
  tasks:
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      with_list:
        - nginx-pod.yaml
        - nginx-deploy.yaml
        - nginx-scaler.yaml
        - sleep-job.yaml
        - sleep-cronjob.yaml
        - sleep-set.yaml
