apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-reader
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["bookofkubernetes.com"]
  resources: ["samples"]
  verbs: ["get", "watch", "list"]
