---
kind: Pod
apiVersion: v1
metadata:
  name: iperf-limit
  annotations:
    kubernetes.io/ingress-bandwidth: 1M
    kubernetes.io/egress-bandwidth: 1M
spec:
  containers:
  - name: iperf
    image: bookofkubernetes/iperf3:stable
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  nodeName: host01
