---
- hosts: masters
  become: yes
  roles:
    - tools
    - containerd
    - crictl
    - k8s
- hosts: remote
  become: yes
  tasks:
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      with_list:
        - etcd-env
        - nginx-cm.yaml
        - nginx-deploy.yaml
        - pgsql-cm.yaml
        - pgsql-ext-cfg.yaml
        - pgsql-ext-sec.yaml
        - pgsql-secret-2.yaml
        - pgsql-secret.yaml
        - pgsql.yaml
