---
- hosts: masters:nodes
  become: yes
  roles:
    - tools
    - cri-o
    - crictl
    - k8s
- hosts: remote
  become: yes
  tasks:
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      with_list:
        - pod.yaml
        - deploy.yaml
        - node-evict.yaml
